<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            ['title' => 'Website Development', 'slug' => 'website-development', 'icon' => 'fa-globe', 'color' => '#00ffb3', 'category' => 'development', 'sort_order' => 1, 'description' => 'Custom website development with modern technologies for fast, scalable, and SEO-optimized web solutions.', 'short_description' => 'Custom, fast, and scalable web solutions.', 'features' => ['Responsive Design', 'SEO Optimized', 'Fast Loading', 'Custom CMS', 'API Integration'], 'meta_title' => 'Top Website Design and Development Company in Ahmedabad, India', 'meta_description' => 'Anprix Solutions is a leading website design and development company in Ahmedabad.', 'meta_keywords' => 'web development company, website development, web design'],
            ['title' => 'WordPress Development', 'slug' => 'wordpress-development', 'icon' => 'fa-wordpress', 'color' => '#00b7ff', 'category' => 'development', 'sort_order' => 2, 'description' => 'Professional WordPress website development with custom themes, plugins, and performance optimization.', 'short_description' => 'Custom WordPress themes and plugins.', 'features' => ['Custom Themes', 'Plugin Development', 'WooCommerce', 'Speed Optimization', 'Security Hardening'], 'meta_title' => 'WordPress Website Development Company in Ahmedabad | Anprix Solutions', 'meta_description' => 'Anprix Solutions is a leading WordPress website development company in Ahmedabad.', 'meta_keywords' => 'wordpress development company, wordpress website development'],
            ['title' => 'eCommerce Development', 'slug' => 'ecommerce-development', 'icon' => 'fa-shopping-cart', 'color' => '#00ffb3', 'category' => 'development', 'sort_order' => 3, 'description' => 'Powerful online stores on Shopify, WooCommerce, Magento, and custom platforms.', 'short_description' => 'Shopify, WooCommerce, and custom stores.', 'features' => ['Shopify Development', 'WooCommerce', 'Payment Gateway', 'Inventory Management', 'Custom Checkout'], 'meta_title' => 'eCommerce Website Development Company in Ahmedabad | Anprix Solutions', 'meta_description' => 'Anprix Solutions is a leading eCommerce website development company in Ahmedabad.', 'meta_keywords' => 'ecommerce development company, shopify development, woocommerce development'],
            ['title' => 'Website Redesign', 'slug' => 'website-redesign', 'icon' => 'fa-palette', 'color' => '#00b7ff', 'category' => 'development', 'sort_order' => 4, 'description' => 'Transform outdated websites into modern, high-performing digital assets with improved UX, speed, and SEO.', 'short_description' => 'Modernize your outdated website.', 'features' => ['Modern UI/UX', 'Speed Optimization', 'Mobile Responsive', 'SEO Preservation', 'Conversion Optimization'], 'meta_title' => 'Website Redesign Services Company in Ahmedabad | Anprix Solutions', 'meta_description' => 'Anprix Solutions is a leading website redesign agency in Ahmedabad.', 'meta_keywords' => 'website redesign services, website redesign company, website redesign agency'],
            ['title' => 'CMS Development', 'slug' => 'cms-development', 'icon' => 'fa-database', 'color' => '#00b7ff', 'category' => 'development', 'sort_order' => 5, 'description' => 'CMS development across WordPress, Shopify, and custom platforms plus eCommerce solutions.', 'short_description' => 'WordPress, Shopify, and custom CMS.', 'features' => ['WordPress CMS', 'Custom CMS', 'Content Management', 'User Roles', 'Multilingual Support'], 'meta_title' => 'CMS Development Company in Ahmedabad | Anprix Solutions', 'meta_description' => 'Anprix offers CMS development across WordPress, Shopify, and custom platforms.', 'meta_keywords' => 'cms development company, cms development services'],
            ['title' => 'SEO Services', 'slug' => 'seo', 'icon' => 'fa-chart-line', 'color' => '#00b7ff', 'category' => 'seo', 'sort_order' => 6, 'description' => 'Expert SEO services to improve rankings, organic traffic, leads, and business growth.', 'short_description' => 'Rank higher on Google.', 'features' => ['Technical SEO', 'On-Page SEO', 'Link Building', 'Keyword Research', 'Analytics & Reporting'], 'meta_title' => 'SEO Company in Ahmedabad | Best SEO Services | Anprix Solutions', 'meta_description' => 'Looking for the best SEO company in Ahmedabad? Anprix Solutions offers expert SEO services.', 'meta_keywords' => 'seo company in ahmedabad, seo services in ahmedabad, best seo company'],
            ['title' => 'Digital Marketing', 'slug' => 'digital-marketing', 'icon' => 'fa-rocket', 'color' => '#00ffb3', 'category' => 'marketing', 'sort_order' => 7, 'description' => 'Full-range digital marketing services to generate leads, increase brand awareness, and drive traffic.', 'short_description' => 'Grow your business online.', 'features' => ['Google Ads', 'Social Media Marketing', 'Content Marketing', 'Email Marketing', 'Conversion Optimization'], 'meta_title' => 'Digital Marketing Agency in Ahmedabad | Anprix Solutions', 'meta_description' => 'Anprix Solutions is a leading digital marketing agency in Ahmedabad.', 'meta_keywords' => 'digital marketing agency in ahmedabad, digital marketing services'],
            ['title' => 'Social Media Marketing', 'slug' => 'social-media-marketing', 'icon' => 'fa-share-alt', 'color' => '#00b7ff', 'category' => 'marketing', 'sort_order' => 8, 'description' => 'Build influence, engage audiences, and convert followers into loyal customers through data-driven strategies.', 'short_description' => 'Grow your social presence.', 'features' => ['Facebook Marketing', 'Instagram Marketing', 'LinkedIn Marketing', 'Content Creation', 'Community Management'], 'meta_title' => 'Best Social Media Marketing Agency in Ahmedabad | Anprix Solutions', 'meta_description' => 'Anprix Solutions is a premier social media marketing agency in Ahmedabad.', 'meta_keywords' => 'social media marketing agency in ahmedabad, social media company'],
            ['title' => 'Google Ads & PPC', 'slug' => 'advertising', 'icon' => 'fa-ad', 'color' => '#00ffb3', 'category' => 'marketing', 'sort_order' => 9, 'description' => 'Google Ads, social media advertising, retargeting, display ads, and PPC campaign management.', 'short_description' => 'Targeted paid advertising.', 'features' => ['Google Ads Management', 'PPC Campaigns', 'Retargeting', 'Display Advertising', 'ROI Tracking'], 'meta_title' => 'Advertising Services in Ahmedabad | Google Ads & PPC | Anprix Solutions', 'meta_description' => 'Anprix offers Google Ads, social media advertising, retargeting, display ads.', 'meta_keywords' => 'advertising services, google ads agency, ppc management'],
            ['title' => 'Branding & Creative', 'slug' => 'branding-creative', 'icon' => 'fa-star', 'color' => '#00b7ff', 'category' => 'branding', 'sort_order' => 10, 'description' => 'Logo design, brand identity, visual storytelling, packaging design, and creative strategy.', 'short_description' => 'Build your brand identity.', 'features' => ['Logo Design', 'Brand Identity', 'Visual Storytelling', 'Packaging Design', 'Creative Strategy'], 'meta_title' => 'Branding & Creative Agency in Ahmedabad | Anprix Solutions', 'meta_description' => 'Anprix offers logo design, brand identity, visual storytelling, packaging design.', 'meta_keywords' => 'branding agency, creative agency, logo design, brand identity'],
        ];

        foreach ($services as $i => $data) {
            Service::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
